export {
  getActiveProducts,
  getFeaturedProducts,
  getNewProducts,
  getProductsByCategory,
  getProductById,
  getProductBySlug,
  searchProducts,
  adminGetAllProducts,
  adminGetProductById,
  adminIsProductSlugTaken,
  adminCreateProduct,
  adminUpdateProduct,
  adminPatchProduct,
  adminDeleteProduct,
  adminReplaceProductImage,
  uploadProductImage,
} from '@/services/productService'

export {
  getActiveCategories,
  getCategoryBySlug,
  adminGetAllCategories,
  adminIsCategorySlugTaken,
  adminCountProductsInCategory,
  adminCreateCategory,
  adminUpdateCategory,
  adminToggleCategoryActive,
  adminDeleteCategory,
  adminReplaceCategoryImage,
} from '@/services/categoryService'
